# Generated by Django 3.1.2 on 2020-11-08 10:12

from django.db import migrations, models
import django.db.models.deletion
import main.validators
from supplies.models import Unit


def make_units(apps, schema_editor):
    Unit.objects.create(name='ml')
    Unit.objects.create(name='l')
    Unit.objects.create(name='g')
    Unit.objects.create(name='kg')
    Unit.objects.create(name='stk')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, validators=[main.validators.validate_item_name])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, validators=[main.validators.validate_item_name])),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True, validators=[main.validators.validate_item_name])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.unit')),
                ('amount', models.IntegerField()),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplies.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='supplies.category')),
            ],
            options={
                'unique_together': {('name', 'category', 'brand', 'unit', 'amount')},
            },
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('best_before_date', models.DateField(blank=True, null=True, verbose_name='best-before date')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplies.supply')),
            ],
        ),

        migrations.RunPython(make_units, reverse_code=lambda *args, **kwargs: True)
    ]
