# Generated by Django 3.1.2 on 2020-11-11 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import main.validators
from supplies.models import Packaging


def make_packagings(apps, schema_editor):
    Packaging.objects.create(name='Konservendose')
    Packaging.objects.create(name='Konservenglas')
    Packaging.objects.create(name='Glas')
    Packaging.objects.create(name='Kunststoffbeutel')
    Packaging.objects.create(name='Glasflasche')
    Packaging.objects.create(name='Kunststoffflasche')
    Packaging.objects.create(name='Tube')
    Packaging.objects.create(name='Aluminium')
    Packaging.objects.create(name='Netz')
    Packaging.objects.create(name='Karton')
    Packaging.objects.create(name='Papier')
    Packaging.objects.create(name='Tetra Pack')


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[main.validators.validate_item_name])),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AddField(
            model_name='supply',
            name='bio_label',
            field=models.BooleanField(default=False, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='supply',
            name='min_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplies.packaging'),
        ),
        migrations.AlterUniqueTogether(
            name='supply',
            unique_together={('name', 'category', 'brand', 'unit', 'amount', 'packaging')},
        ),

        migrations.RunPython(make_packagings, reverse_code=lambda *args, **kwargs: True)
    ]
