# Generated by Django 3.1.2 on 2020-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_auto_20201111_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitem',
            name='checkout_date',
            field=models.DateField(blank=True, null=True, verbose_name='checkout date'),
        ),
    ]
