# Generated by Django 3.1.2 on 2020-12-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_auto_20201215_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyitem',
            name='supply',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('supply', 'brand', 'unit', 'amount', 'packaging')},
        ),
        migrations.AlterUniqueTogether(
            name='supply',
            unique_together={('name', 'category')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='bio_label',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='unit',
        ),
    ]
