# Generated by Django 3.1.2 on 2020-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_auto_20201215_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('supply', 'name', 'brand', 'unit', 'amount', 'packaging')},
        ),
    ]
