# Generated by Django 3.1.2 on 2020-10-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping_book', '0002_auto_20201012_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='parent_identifier',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
