name: Publish Container
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5.5.0
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/cupracer/family-tools/family-tools
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PKG_GITHUB_TOKEN }}
          dockerfile: Dockerfile
          platforms: linux/amd64,linux/arm64
